---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Disable default apache host.
  file: >
    path="{{ apache_default_vhost }}"
    state=absent
  notify: restart apache
  when:
    - apache_disable_default_site
    - apache_default_vhost is defined

- name: Add apache vhosts configuration.
  template: >
    src=vhosts.conf.j2
    dest={{ apache_conf_path }}/{{ "%03d" | format(item.0) }}-{{ item.1.servername }}.conf
    owner=root group=root mode=644
  with_indexed_items: apache_vhosts
  notify: restart apache
  when: apache_create_vhosts

- name: Ensure Apache is started and enabled on boot.
  service: >
    name={{ apache_daemon }}
    state=started
    enabled=yes

# ex: ft=ansible et ts=2 sw=2:
