---
- name: Ensure Apache is installed (RedHat).
  yum: >
    name={{ item }}
    state=installed
    enablerepo={{ apache_enablerepo }}
  with_items: apache_packages

- name: Configure Apache Vhost ports (RedHat).
  replace: >
    dest={{ apache_server_root }}/conf/{{ apache_daemon }}.conf
    regexp="(\nNameVirtualHost [^\n]+)+"
    replace="{% for item in apache_listen_ports %}\nNameVirtualHost *:{{ item }}{% endfor %}"

- name: Configure Apache listening ports (RedHat).
  replace: >
    dest={{ apache_server_root }}/conf/{{ apache_daemon }}.conf
    regexp="(\nListen [^\n]+)+"
    replace="{% for item in apache_listen_ports %}\nListen {{ item }}{% endfor %}"
  notify: restart apache
