---
- name: Ensure Apache is installed (RedHat).
  yum: >
    name={{ item }}
    state=installed
    enablerepo={{ apache_enablerepo }}
  with_items: apache_packages

- name: Configure Apache (RedHat).
  lineinfile: >
    dest={{ apache_server_root }}/conf/{{ apache_daemon }}.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }
  - {
    regexp: "^NameVirtualHost ",
    line: "NameVirtualHost *:{{ apache_listen_port }}"
  }
  notify: restart apache

- name: Configure apache timeouts and keepalives (RedHat).
  lineinfile: >
    dest="{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
  - {
    regexp: "^Timeout ",
    line: "Timeout {{ apache_timeout }}"
  }
  - {
    regexp: "^KeepAlive ",
    line: "KeepAlive {% if apache_keepalive is string %}{{ apache_keepalive }}{% else %}{{ 'On' if apache_keepalive else 'Off' }}{% endif %}"
  }
  - {
    regexp: "^KeepAliveTimeout ",
    line: "KeepAliveTimeout {{ apache_keepalive_timeout }}"
  }
  - {
    regexp: "^MaxKeepAliveRequests ",
    line: "MaxKeepAliveRequests {{ apache_max_keepalive_reqs }}"
  }
  - {
    regexp: "^ServerTokens ",
    line: "ServerTokens {{ apache_server_tokens }}"
  }
  - {
    regexp: "^ServerSignature ",
    line: "ServerSignature {% if apache_server_signature is string %}{{ apache_server_signature }}{% else %}{{ 'On' if apache_server_signature else 'Off' }}{% endif %}"
  }
  - {
    regexp: "^TraceEnable ",
    line: "TraceEnable {% if apache_trace_enable is string %}{{ apache_trace_enable }}{% else %}{{ 'On' if apache_trace_enable else 'Off' }}{% endif %}"
  }
  notify: restart apache
